// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQRBQazjbyvVZwdf1rOTBWGeYeISH1rMU',
    appId: '1:468383821013:web:394ad8899cdd3ac22a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    authDomain: 'khalid-projects.firebaseapp.com',
    storageBucket: 'khalid-projects.appspot.com',
    measurementId: 'G-P9K6RCS6YC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZbwDbEg0x1O5FGcsXQFFOP7ny1tlC0-s',
    appId: '1:468383821013:android:aec1f4b30a1fd47c2a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    storageBucket: 'khalid-projects.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoD_LrQVrWJf5Nnx-XpJ5u5UZ1N9ktnG8',
    appId: '1:468383821013:ios:901d19679ae80d142a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    storageBucket: 'khalid-projects.appspot.com',
    androidClientId: '468383821013-87ltnh4os3rr3p5pn784ui79q0vrdok8.apps.googleusercontent.com',
    iosClientId: '468383821013-ee30431glk8bs11l2o1m022kn0lk75ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.khalidprojects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoD_LrQVrWJf5Nnx-XpJ5u5UZ1N9ktnG8',
    appId: '1:468383821013:ios:901d19679ae80d142a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    storageBucket: 'khalid-projects.appspot.com',
    androidClientId: '468383821013-87ltnh4os3rr3p5pn784ui79q0vrdok8.apps.googleusercontent.com',
    iosClientId: '468383821013-ee30431glk8bs11l2o1m022kn0lk75ep.apps.googleusercontent.com',
    iosBundleId: 'com.example.khalidprojects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQRBQazjbyvVZwdf1rOTBWGeYeISH1rMU',
    appId: '1:468383821013:web:1d0046edd50beabe2a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    authDomain: 'khalid-projects.firebaseapp.com',
    storageBucket: 'khalid-projects.appspot.com',
    measurementId: 'G-0489MXXW9G',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBQRBQazjbyvVZwdf1rOTBWGeYeISH1rMU',
    appId: '1:468383821013:web:af74ece4767f1e022a465c',
    messagingSenderId: '468383821013',
    projectId: 'khalid-projects',
    authDomain: 'khalid-projects.firebaseapp.com',
    storageBucket: 'khalid-projects.appspot.com',
    measurementId: 'G-F4ZCLJ46ZY',
  );
}
